name: Swift

on:

  pull_request:
     branches: [main, develop]

jobs:

  build:

    runs-on: macOS-latest
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=14.4,name=iPhone 12']
    steps:

    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Test
      run: |
        pwd
        xcodebuild build-for-testing \
        -scheme DanceNow \
        -destination 'platform=iOS Simulator,name=iPhone 11 Pro' \
        -derivedDataPath build \
        | xcpretty

