name: Swift

on:
  pull_request:
     branches: [main, develop]

jobs:
  build:
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=14.4,name=iPhone 12']
          
    steps:
    - name: Checkout
      uses: actions/checkout@master
     
    - name: Build and Test
      run: |
        pwd
        xcodebuild clean test -project DanceNow.xcodeproj -scheme DanceNow -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
      env: 
        destination: ${{ matrix.destination}}
